### ISSUE TITLE
Why `rust.cargo` and not `cargo`?

### ISSUE THREAD

**Issue by jean** [dawidd6/rust-snap#2]
This snap creates `rust.cargo` and `rust.rustc`:

```
lrwxrwxrwx 1 root root 13 Jan  4 11:55 rust.cargo -> /usr/bin/snap
lrwxrwxrwx 1 root root 13 Jan  4 11:55 rust.rustc -> /usr/bin/snap
```

All the makefiles I encounter use `cargo`. `ln -s rust.cargo cargo` doesn't work (`cargo` runs `snap` instead).

**Comment by dawidd6** [comment]
Citing the official docs:
```
To avoid the potential conflict of snaps exposing applications with the same name, every snap has a namespace reserved for itself. The namespace uses the following syntax:

<snap name>
<snap name>.<application name>

The first option is used automatically when the exposed application name matches the name of the snap, such as with vlc. The second option is used for every other case.
```

https://snapcraft.io/docs/commands-and-aliases

**Comment by jean** [comment]
Ah, OK, got it, thank you!

In this case I guess the rust snap needs a couple of aliases: _The namespace syntax (see above) is effective at preventing conflicts, but it’s not ideal when applications have well known names that third-party scripts depend upon. This is where aliases are useful._

(I ran into this while building `gnvim` https://github.com/vhakulinen/gnvim/issues/125#issuecomment-570865440)

**Comment by dawidd6** [comment]
I'm not maintaining this snap anymore. In fact I would delete it altogether, cause it's causing more trouble than benefits.

As a workaround you can define aliases yourself as the docs say.

**Comment by jean** [comment]
Yes, I stumbled across it at https://snapcraft.io/rust .. would be good to delete it.
